[environments.dev]
# theme = "147450003677"
store = "petschoice-club.myshopify.com"
password = "shptka_04c84a410ab504e50f0b457dcc5894a6"
store-password = "admin"
# ignore = "sections/header.liquid"
# live = true
allow-live = true
output = "json"
path = "./impact"
theme-editor-sync = true

[environments.dev-prod-live]
# theme = "147450003677"
store = "419319-9b.myshopify.com"
password = "shptka_317fef5eb17a66c2e49c58e6ab96d59f"
# store-password = "admin"
# ignore = "sections/header.liquid"
live = true
allow-live = true
nodelete = true
path = "./impact"
theme-editor-sync = true