# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "496190862dbfed43f8c6ad645d8e81db"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "petschoice"
handle = "petschoice"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "checkout-works.myshopify.com"
include_config_on_deploy = true
